In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

data_dictionary.txt
macro.csv
sample_submission.csv
test.csv
train.csv

In [2]:
import os
print(os.getcwd())

/home/xinjun/kaggle/house_price/working

In [4]:
train_dataset = pd.read_csv("../input/train.csv")
train_dataset.head()

,id,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,price_doc
0,1,2011-08-20,43,27.0,4.0,NaN,NaN,NaN,NaN,NaN,...,9,4,0,13,22,1,0,52,4,5850000
1,2,2011-08-23,34,19.0,3.0,NaN,NaN,NaN,NaN,NaN,...,15,3,0,15,29,1,10,66,14,6000000
2,3,2011-08-27,43,29.0,2.0,NaN,NaN,NaN,NaN,NaN,...,10,3,0,11,27,0,4,67,10,5700000
3,4,2011-09-01,89,50.0,9.0,NaN,NaN,NaN,NaN,NaN,...,11,2,1,4,4,0,0,26,3,13100000
4,5,2011-09-05,77,77.0,4.0,NaN,NaN,NaN,NaN,NaN,...,319,108,17,135,236,2,91,195,14,16331452

In [5]:
null_count = train_dataset.isnull().sum().sort_values(ascending = False)
null_percent = ( train_dataset.isnull().sum() / train_dataset.isnull().count()).sort_values(ascending = False)
null_info = pd.concat([null_count, null_percent], axis = 1, keys = ['count', 'percent'])
print(null_info)

                                       count   percent
hospital_beds_raion                    14441  0.473926
build_year                             13605  0.446490
state                                  13559  0.444980
cafe_avg_price_500                     13281  0.435857
cafe_sum_500_max_price_avg             13281  0.435857
cafe_sum_500_min_price_avg             13281  0.435857
max_floor                               9572  0.314135
material                                9572  0.314135
num_room                                9572  0.314135
kitch_sq                                9572  0.314135
preschool_quota                         6688  0.219487
school_quota                            6685  0.219389
cafe_sum_1000_min_price_avg             6524  0.214105
cafe_sum_1000_max_price_avg             6524  0.214105
cafe_avg_price_1000                     6524  0.214105
life_sq                                 6383  0.209478
build_count_frame                       4991  0.163795
build_count_1971-1995                   4991  0.163795
build_count_block                       4991  0.163795
raion_build_count_with_material_info    4991  0.163795
build_count_after_1995                  4991  0.163795
build_count_brick                       4991  0.163795
build_count_wood                        4991  0.163795
build_count_mix                         4991  0.163795
build_count_1921-1945                   4991  0.163795
build_count_panel                       4991  0.163795
build_count_foam                        4991  0.163795
build_count_slag                        4991  0.163795
raion_build_count_with_builddate_info   4991  0.163795
build_count_monolith                    4991  0.163795
...                                      ...       ...
cafe_count_1500_na_price                   0  0.000000
cafe_count_1500                            0  0.000000
trc_sqm_1500                               0  0.000000
trc_count_1500                             0  0.000000
office_sqm_1500                            0  0.000000
office_count_1500                          0  0.000000
prom_part_1500                             0  0.000000
green_part_1500                            0  0.000000
market_count_1000                          0  0.000000
sport_count_1000                           0  0.000000
leisure_count_1000                         0  0.000000
mosque_count_1000                          0  0.000000
church_count_1000                          0  0.000000
cafe_count_1000_price_high                 0  0.000000
sport_count_500                            0  0.000000
cafe_count_1000_price_4000                 0  0.000000
cafe_count_1000_price_2500                 0  0.000000
cafe_count_1000_price_1500                 0  0.000000
cafe_count_1000_price_1000                 0  0.000000
cafe_count_1000_price_500                  0  0.000000
cafe_count_1000_na_price                   0  0.000000
cafe_count_1000                            0  0.000000
trc_sqm_1000                               0  0.000000
trc_count_1000                             0  0.000000
office_sqm_1000                            0  0.000000
office_count_1000                          0  0.000000
prom_part_1000                             0  0.000000
green_part_1000                            0  0.000000
market_count_500                           0  0.000000
id                                         0  0.000000

[292 rows x 2 columns]

In [6]:
print(train_dataset.columns.values)

['id' 'timestamp' 'full_sq' 'life_sq' 'floor' 'max_floor' 'material'
 'build_year' 'num_room' 'kitch_sq' 'state' 'product_type' 'sub_area'
 'area_m' 'raion_popul' 'green_zone_part' 'indust_part'
 'children_preschool' 'preschool_quota' 'preschool_education_centers_raion'
 'children_school' 'school_quota' 'school_education_centers_raion'
 'school_education_centers_top_20_raion' 'hospital_beds_raion'
 'healthcare_centers_raion' 'university_top_20_raion' 'sport_objects_raion'
 'additional_education_raion' 'culture_objects_top_25'
 'culture_objects_top_25_raion' 'shopping_centers_raion' 'office_raion'
 'thermal_power_plant_raion' 'incineration_raion' 'oil_chemistry_raion'
 'radiation_raion' 'railroad_terminal_raion' 'big_market_raion'
 'nuclear_reactor_raion' 'detention_facility_raion' 'full_all' 'male_f'
 'female_f' 'young_all' 'young_male' 'young_female' 'work_all' 'work_male'
 'work_female' 'ekder_all' 'ekder_male' 'ekder_female' '0_6_all' '0_6_male'
 '0_6_female' '7_14_all' '7_14_male' '7_14_female' '0_17_all' '0_17_male'
 '0_17_female' '16_29_all' '16_29_male' '16_29_female' '0_13_all'
 '0_13_male' '0_13_female' 'raion_build_count_with_material_info'
 'build_count_block' 'build_count_wood' 'build_count_frame'
 'build_count_brick' 'build_count_monolith' 'build_count_panel'
 'build_count_foam' 'build_count_slag' 'build_count_mix'
 'raion_build_count_with_builddate_info' 'build_count_before_1920'
 'build_count_1921-1945' 'build_count_1946-1970' 'build_count_1971-1995'
 'build_count_after_1995' 'ID_metro' 'metro_min_avto' 'metro_km_avto'
 'metro_min_walk' 'metro_km_walk' 'kindergarten_km' 'school_km' 'park_km'
 'green_zone_km' 'industrial_km' 'water_treatment_km' 'cemetery_km'
 'incineration_km' 'railroad_station_walk_km' 'railroad_station_walk_min'
 'ID_railroad_station_walk' 'railroad_station_avto_km'
 'railroad_station_avto_min' 'ID_railroad_station_avto'
 'public_transport_station_km' 'public_transport_station_min_walk'
 'water_km' 'water_1line' 'mkad_km' 'ttk_km' 'sadovoe_km' 'bulvar_ring_km'
 'kremlin_km' 'big_road1_km' 'ID_big_road1' 'big_road1_1line'
 'big_road2_km' 'ID_big_road2' 'railroad_km' 'railroad_1line'
 'zd_vokzaly_avto_km' 'ID_railroad_terminal' 'bus_terminal_avto_km'
 'ID_bus_terminal' 'oil_chemistry_km' 'nuclear_reactor_km' 'radiation_km'
 'power_transmission_line_km' 'thermal_power_plant_km' 'ts_km'
 'big_market_km' 'market_shop_km' 'fitness_km' 'swim_pool_km' 'ice_rink_km'
 'stadium_km' 'basketball_km' 'hospice_morgue_km' 'detention_facility_km'
 'public_healthcare_km' 'university_km' 'workplaces_km'
 'shopping_centers_km' 'office_km' 'additional_education_km' 'preschool_km'
 'big_church_km' 'church_synagogue_km' 'mosque_km' 'theater_km' 'museum_km'
 'exhibition_km' 'catering_km' 'ecology' 'green_part_500' 'prom_part_500'
 'office_count_500' 'office_sqm_500' 'trc_count_500' 'trc_sqm_500'
 'cafe_count_500' 'cafe_sum_500_min_price_avg' 'cafe_sum_500_max_price_avg'
 'cafe_avg_price_500' 'cafe_count_500_na_price' 'cafe_count_500_price_500'
 'cafe_count_500_price_1000' 'cafe_count_500_price_1500'
 'cafe_count_500_price_2500' 'cafe_count_500_price_4000'
 'cafe_count_500_price_high' 'big_church_count_500' 'church_count_500'
 'mosque_count_500' 'leisure_count_500' 'sport_count_500'
 'market_count_500' 'green_part_1000' 'prom_part_1000' 'office_count_1000'
 'office_sqm_1000' 'trc_count_1000' 'trc_sqm_1000' 'cafe_count_1000'
 'cafe_sum_1000_min_price_avg' 'cafe_sum_1000_max_price_avg'
 'cafe_avg_price_1000' 'cafe_count_1000_na_price'
 'cafe_count_1000_price_500' 'cafe_count_1000_price_1000'
 'cafe_count_1000_price_1500' 'cafe_count_1000_price_2500'
 'cafe_count_1000_price_4000' 'cafe_count_1000_price_high'
 'big_church_count_1000' 'church_count_1000' 'mosque_count_1000'
 'leisure_count_1000' 'sport_count_1000' 'market_count_1000'
 'green_part_1500' 'prom_part_1500' 'office_count_1500' 'office_sqm_1500'
 'trc_count_1500' 'trc_sqm_1500' 'cafe_count_1500'
 'cafe_sum_1500_min_price_avg' 'cafe_sum_1500_max_price_avg'
 'cafe_avg_price_1500' 'cafe_count_1500_na_price'
 'cafe_count_1500_price_500' 'cafe_count_1500_price_1000'
 'cafe_count_1500_price_1500' 'cafe_count_1500_price_2500'
 'cafe_count_1500_price_4000' 'cafe_count_1500_price_high'
 'big_church_count_1500' 'church_count_1500' 'mosque_count_1500'
 'leisure_count_1500' 'sport_count_1500' 'market_count_1500'
 'green_part_2000' 'prom_part_2000' 'office_count_2000' 'office_sqm_2000'
 'trc_count_2000' 'trc_sqm_2000' 'cafe_count_2000'
 'cafe_sum_2000_min_price_avg' 'cafe_sum_2000_max_price_avg'
 'cafe_avg_price_2000' 'cafe_count_2000_na_price'
 'cafe_count_2000_price_500' 'cafe_count_2000_price_1000'
 'cafe_count_2000_price_1500' 'cafe_count_2000_price_2500'
 'cafe_count_2000_price_4000' 'cafe_count_2000_price_high'
 'big_church_count_2000' 'church_count_2000' 'mosque_count_2000'
 'leisure_count_2000' 'sport_count_2000' 'market_count_2000'
 'green_part_3000' 'prom_part_3000' 'office_count_3000' 'office_sqm_3000'
 'trc_count_3000' 'trc_sqm_3000' 'cafe_count_3000'
 'cafe_sum_3000_min_price_avg' 'cafe_sum_3000_max_price_avg'
 'cafe_avg_price_3000' 'cafe_count_3000_na_price'
 'cafe_count_3000_price_500' 'cafe_count_3000_price_1000'
 'cafe_count_3000_price_1500' 'cafe_count_3000_price_2500'
 'cafe_count_3000_price_4000' 'cafe_count_3000_price_high'
 'big_church_count_3000' 'church_count_3000' 'mosque_count_3000'
 'leisure_count_3000' 'sport_count_3000' 'market_count_3000'
 'green_part_5000' 'prom_part_5000' 'office_count_5000' 'office_sqm_5000'
 'trc_count_5000' 'trc_sqm_5000' 'cafe_count_5000'
 'cafe_sum_5000_min_price_avg' 'cafe_sum_5000_max_price_avg'
 'cafe_avg_price_5000' 'cafe_count_5000_na_price'
 'cafe_count_5000_price_500' 'cafe_count_5000_price_1000'
 'cafe_count_5000_price_1500' 'cafe_count_5000_price_2500'
 'cafe_count_5000_price_4000' 'cafe_count_5000_price_high'
 'big_church_count_5000' 'church_count_5000' 'mosque_count_5000'
 'leisure_count_5000' 'sport_count_5000' 'market_count_5000' 'price_doc']